# Functions

In [15]:
import statistics as stats
x = list(range(0,21,3))

In [16]:
len(x)

7

In [18]:
print(max(x))
print(min(x))
print("mean", stats.mean(x), )


18
0
mean 9


In [62]:
def addi (x, y):
    print ("Sum is ",x+y)
addi(5,5)

Sum is  10


---

### Scrapy 
---

In [2]:
import scrapy
from scrapy.crawler import CrawlerProcess 

In [7]:
import numpy as np
l = np.array([1,2,3,4]) #Array of same data type
l1 = np.array([1,True, 1.01]) #will convert all data type to something else
l1

array([1.  , 1.  , 1.01])

In [8]:
l1[:3]

array([1.  , 1.  , 1.01])

---
Creating a view of array changes the ARRAY itself...Not the klist talking about array

In [50]:
arr = np.array([1,2,3,4,5,6])
v = np.array(arr[1:3])
v[0]

2

In [51]:
v[0] = 100 # will also change a[0]
v

array([100,   3])

In [52]:
arr

array([1, 2, 3, 4, 5, 6])