# Matrix

#---
#1. from numpy as np.array(data) --> will convert it to array

#2. np.reshape(data, (tuple(row, column)), Order='C'|'F') 

#data -> data to be reshaped
#tuple-> desrired number of row and column given as immutable tuple
    #e.g  [:, 2] all row with column 2
    # [2: 3]  2 row and 3rd column
#---

In [2]:
import numpy as np

data = np.arange(0, 20)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [35]:
_as_matrix = np.reshape(data, (4 , 5), order='C')
print(_as_matrix)
print("------")
_as_matrixC = np.reshape(data, (4, 5), order="F")
print(_as_matrixC)
_as_matrix+_as_matrixC

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
------
[[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]


array([[ 0,  5, 10, 15, 20],
       [ 6, 11, 16, 21, 26],
       [12, 17, 22, 27, 32],
       [18, 23, 28, 33, 38]])

In [4]:
_as_matrix[:,2]

array([ 2,  7, 12, 17])

In [6]:
_as_matrix[:,-5]

array([ 0,  5, 10, 15])

In [7]:
_as_matrix[-4, :3]

array([0, 1, 2])

In [13]:
_as_matrix[2, -5: -1]

array([10, 11, 12, 13])

In [30]:
_as_matrix[2, 0]

10

In [36]:
_as_matrixC[-4,-3]

8

---

### As OOP  directly from object instead of np.reshape()

---

In [39]:
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [56]:
mat1 = data.reshape(4,5)
mat1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [59]:
l1=[1,2,3]
l2=["a","b"]
print(np.array((l1,l2)))

[list([1, 2, 3]) list(['a', 'b'])]


In [60]:
type(l1)

list